#!/bin/sh

# PROVIDE: cdaemon
# REQUIRE: networking
# KEYWORD: shutdown

. /etc/rc.subr
  
name="cdaemon"
rcvar="${name}_enable"
load_rc_config $name
: ${cdaemon_enable:="NO"}
: ${cdaemon_path:="/usr/local/www/${name}.com"}
: ${cdaemon_log:="/var/log/${name}.log"}

user="www"
pidfile="/var/run/${name}.pid"

start_precmd="${name}_prestart"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

cdaemon_prestart() {
	export LD_LIBRARY_PATH="/usr/local/lib"
	export NODE_ENV="production"
}

cdaemon_start() {
	if [ $(id -u) -eq 0 ]; then
		daemon -o $cdaemon_log -P $pidfile -t "${name}d" -u $user \
			npm run --prefix $cdaemon_path start &
		echo "${name} server started"
	else
		echo "insufficient permissions"
	fi
}

cdaemon_stop() {
	if [ $(id -u) -eq 0 ]; then
		if [ ${cdaemon_pid:=$(check_pidfile $pidfile "daemon")} ]; then
			pkill -P $cdaemon_pid
			wait_for_pids $cdaemon_pid
			echo "${name} stopped successfully"
		else
			echo "${name} is not active"
		fi
	else
		echo "insufficient permissions"
	fi
}

run_rc_command "$1"
